{
  "updates": [
    {
      "commit-message": {
        "include": "scope",
        "prefix": "chore"
      },
      "directory": "/",
      "groups": {
        "everything": {
          "patterns": [
            "*"
          ]
        }
      },
      "package-ecosystem": "cargo",
      "schedule": {
        "interval": "daily"
      }
    }
  ],
  "version": 2
}
