use crate::lints;

lints! {
    bool_comparison,
    empty_let_in,
    manual_inherit,
    manual_inherit_from,
    legacy_let_syntax,
    collapsible_let_in,
    eta_reduction,
    useless_parens,
    // unquoted_splice,
    empty_pattern,
    redundant_pattern_bind,
    unquoted_uri,
    empty_inherit,
    deprecated_to_path,
    bool_simplification,
    useless_has_attr,
    repeated_keys,
    empty_list_concat,
    ineffective_string_escape,
    negated_is_null,
    optionals_string,
    optional_list_in_flat_context,
    deprecated_stdenv_lib,
    fetcher_hash_field,
    broad_with_lib,
    with_lexical_collision
}
