name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: build statix
      run: nix build -L
    - name: test statix
      run: nix flake check
    - name: build statix and install statix in flake-compat mode
      run: nix-env -if default.nix
