{
  "jobs": {
    "check": {
      "needs": "get-check-names",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4"
        },
        {
          "uses": "cachix/install-nix-action@v31",
          "with": {
            "github_access_token": "${{ secrets.GITHUB_TOKEN }}"
          }
        },
        {
          "run": "nix --accept-flake-config build '.#checks.x86_64-linux.\"${{ matrix.checks }}\"'\n"
        }
      ],
      "strategy": {
        "matrix": {
          "checks": "${{ fromJson(needs.get-check-names.outputs.checks) }}"
        }
      }
    },
    "get-check-names": {
      "outputs": {
        "checks": "${{ steps.get-check-names.outputs.checks }}"
      },
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4"
        },
        {
          "uses": "cachix/install-nix-action@v31",
          "with": {
            "github_access_token": "${{ secrets.GITHUB_TOKEN }}"
          }
        },
        {
          "id": "get-check-names",
          "run": "checks=\"$(nix --accept-flake-config eval --json .#checks.x86_64-linux --apply builtins.attrNames)\"\necho \"checks=$checks\" >> $GITHUB_OUTPUT\n"
        }
      ]
    },
    "legacy": {
      "name": "Build statix via flake-compat and install it using `nix-env`",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4"
        },
        {
          "uses": "cachix/install-nix-action@v31",
          "with": {
            "github_access_token": "${{ secrets.GITHUB_TOKEN }}"
          }
        },
        {
          "run": "nix-env --install --file default.nix"
        }
      ]
    }
  },
  "name": "Check",
  "on": {
    "pull_request": {},
    "push": {},
    "workflow_dispatch": {}
  }
}
