{
  "jobs": {
    "check": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v5"
        },
        {
          "uses": "cachix/install-nix-action@master",
          "with": {
            "extra_nix_config": "keep-env-derivations = true\nkeep-outputs = true\n",
            "github_access_token": "${{ secrets.GITHUB_TOKEN }}"
          }
        },
        {
          "run": "nix --accept-flake-config flake check --print-build-logs"
        }
      ]
    }
  },
  "name": "Check",
  "on": {
    "pull_request": {},
    "push": {},
    "workflow_dispatch": {}
  }
}
